import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  detectRequiredEnvVars,
  readEnvLocal,
  hasDirectusCmsDep,
} from '../../deploy-directus-site/src/env-vars.js';
import { generatePackageJson, generateEnvLocal } from '../../create-directus-site/src/generators.js';
import { createCoreOnlySiteOptions, createFullSiteOptions } from './helpers/fixtures.js';
import { createTmpDir, removeTmpDir } from './helpers/cleanup.js';

let tmpDir: string;

beforeEach(() => {
  tmpDir = createTmpDir();
});

afterEach(() => {
  removeTmpDir(tmpDir);
});

// ---------------------------------------------------------------------------
// detectRequiredEnvVars()
// ---------------------------------------------------------------------------
describe('detectRequiredEnvVars', () => {
  it('core-only package.json returns 2 env vars', () => {
    const pkgJson = generatePackageJson(createCoreOnlySiteOptions());
    fs.writeFileSync(path.join(tmpDir, 'package.json'), pkgJson);

    const vars = detectRequiredEnvVars(tmpDir);
    expect(vars).toHaveLength(2);
    expect(vars.map((v) => v.key)).toEqual([
      'NEXT_PUBLIC_DIRECTUS_URL',
      'DIRECTUS_STATIC_TOKEN',
    ]);
  });

  it('full config returns 15 env vars (base + admin + preview + webhooks + stripe + auth + email)', () => {
    const pkgJson = generatePackageJson(createFullSiteOptions());
    fs.writeFileSync(path.join(tmpDir, 'package.json'), pkgJson);

    const vars = detectRequiredEnvVars(tmpDir);
    expect(vars).toHaveLength(15);
    expect(vars.map((v) => v.key)).toEqual([
      'NEXT_PUBLIC_DIRECTUS_URL',
      'DIRECTUS_STATIC_TOKEN',
      'ADMIN_PASSWORD',
      'ADMIN_SECRET',
      'PREVIEW_SECRET',
      'DIRECTUS_ADMIN_TOKEN',
      'WEBHOOK_SECRET',
      'STRIPE_SECRET_KEY',
      'STRIPE_WEBHOOK_SECRET',
      'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY',
      'NEXT_PUBLIC_SUPABASE_URL',
      'NEXT_PUBLIC_SUPABASE_ANON_KEY',
      'SUPABASE_SERVICE_ROLE_KEY',
      'RESEND_API_KEY',
      'EMAIL_FROM',
    ]);
  });

  it('all vars are marked required: true', () => {
    const pkgJson = generatePackageJson(createFullSiteOptions());
    fs.writeFileSync(path.join(tmpDir, 'package.json'), pkgJson);

    const vars = detectRequiredEnvVars(tmpDir);
    expect(vars.every((v) => v.required)).toBe(true);
  });

  it('throws for missing package.json', () => {
    expect(() => detectRequiredEnvVars(tmpDir)).toThrow('No package.json found');
  });
});

// ---------------------------------------------------------------------------
// readEnvLocal()
// ---------------------------------------------------------------------------
describe('readEnvLocal', () => {
  it('parses KEY=value pairs', () => {
    fs.writeFileSync(path.join(tmpDir, '.env.local'), 'FOO=bar\nBAZ=qux\n');
    const vars = readEnvLocal(tmpDir);
    expect(vars).toEqual({ FOO: 'bar', BAZ: 'qux' });
  });

  it('ignores comments and blank lines', () => {
    fs.writeFileSync(path.join(tmpDir, '.env.local'), '# comment\n\nFOO=bar\n  \n# another\n');
    const vars = readEnvLocal(tmpDir);
    expect(vars).toEqual({ FOO: 'bar' });
  });

  it('strips surrounding quotes', () => {
    fs.writeFileSync(path.join(tmpDir, '.env.local'), 'A="double"\nB=\'single\'\nC=none\n');
    const vars = readEnvLocal(tmpDir);
    expect(vars.A).toBe('double');
    expect(vars.B).toBe('single');
    expect(vars.C).toBe('none');
  });

  it('returns {} for missing file', () => {
    const vars = readEnvLocal(tmpDir);
    expect(vars).toEqual({});
  });
});

// ---------------------------------------------------------------------------
// hasDirectusCmsDep()
// ---------------------------------------------------------------------------
describe('hasDirectusCmsDep', () => {
  it('returns true for project with @mkuesta/core', () => {
    const pkgJson = generatePackageJson(createCoreOnlySiteOptions());
    fs.writeFileSync(path.join(tmpDir, 'package.json'), pkgJson);
    expect(hasDirectusCmsDep(tmpDir)).toBe(true);
  });

  it('returns false for non-CMS project', () => {
    fs.writeFileSync(path.join(tmpDir, 'package.json'), JSON.stringify({
      name: 'plain-project',
      dependencies: { express: '^4.0.0' },
    }));
    expect(hasDirectusCmsDep(tmpDir)).toBe(false);
  });

  it('returns false for missing package.json', () => {
    expect(hasDirectusCmsDep(tmpDir)).toBe(false);
  });

  it('parses the .env.local generated by generateEnvLocal — keys are present', () => {
    const opts = createFullSiteOptions();
    const envContent = generateEnvLocal(opts);
    fs.writeFileSync(path.join(tmpDir, '.env.local'), envContent);

    const vars = readEnvLocal(tmpDir);
    expect(vars).toHaveProperty('NEXT_PUBLIC_DIRECTUS_URL');
    expect(vars).toHaveProperty('DIRECTUS_STATIC_TOKEN');
    expect(vars).toHaveProperty('ADMIN_PASSWORD');
    expect(vars).toHaveProperty('ADMIN_SECRET');
    expect(vars).toHaveProperty('PREVIEW_SECRET');
    expect(vars).toHaveProperty('DIRECTUS_ADMIN_TOKEN');
    expect(vars).toHaveProperty('WEBHOOK_SECRET');
    expect(vars).toHaveProperty('STRIPE_SECRET_KEY');
    expect(vars).toHaveProperty('STRIPE_WEBHOOK_SECRET');
    expect(vars).toHaveProperty('NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY');
    expect(vars).toHaveProperty('NEXT_PUBLIC_SUPABASE_URL');
    expect(vars).toHaveProperty('NEXT_PUBLIC_SUPABASE_ANON_KEY');
    expect(vars).toHaveProperty('SUPABASE_SERVICE_ROLE_KEY');
    expect(vars).toHaveProperty('RESEND_API_KEY');
    expect(vars).toHaveProperty('EMAIL_FROM');
  });
});
